name: Execute Binance Trading Script

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '*/5 * * * *'

jobs:
  execute-script:
    if: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python environment in Docker
      uses: docker://python:3.9

    - name: Install dependencies and run script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        floor_price: ${{ secrets.floor_price }}
        ceil_price: ${{ secrets.ceil_price }}
      run: |
        make

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "tu_email@github.com"
        git add data/balance.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update balance.json" && git push)
